// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjPWMWQcSWq0CYujgAZbKqu4O5cWWBrU',
    appId: '1:816889092774:web:be7101deb63b6168cd3267',
    messagingSenderId: '816889092774',
    projectId: 'fixy-pro-c83ab',
    authDomain: 'fixy-pro-c83ab.firebaseapp.com',
    storageBucket: 'fixy-pro-c83ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmgIlCSFx4CLVL03P6k-fWrEcIkPDAPM',
    appId: '1:816889092774:android:26a1e25f3ab46e0ccd3267',
    messagingSenderId: '816889092774',
    projectId: 'fixy-pro-c83ab',
    storageBucket: 'fixy-pro-c83ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxjPWMWQcSWq0CYujgAZbKqu4O5cWWBrU',
    appId: '1:816889092774:web:130454fc07324e21cd3267',
    messagingSenderId: '816889092774',
    projectId: 'fixy-pro-c83ab',
    authDomain: 'fixy-pro-c83ab.firebaseapp.com',
    storageBucket: 'fixy-pro-c83ab.firebasestorage.app',
  );
}
